# NFS PersistentVolume
apiVersion: v1
kind: PersistentVolume
metadata:
  name: rabbitmq-pv-nfs
  namespace: egov-infra
spec:
  capacity:
    storage: 10Mi
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain
  storageClassName: standard
  nfs:
    server: 192.168.64.1
    path: "/Users/chrisyoon/nfs-share/data/rabbitmq"

---
# NFS PersistentVolumeClaim
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: rabbitmq-pvc-nfs
  namespace: egov-infra
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 10Mi
  volumeName: rabbitmq-pv-nfs
  storageClassName: standard
