# Config PV/PVC - NFS
apiVersion: v1
kind: PersistentVolume
metadata:
  name: egov-search-config-pv-nfs
  namespace: egov-app
spec:
  capacity:
    storage: 1Mi
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain
  storageClassName: standard
  nfs:
    server: 192.168.64.1
    path: "/Users/chrisyoon/nfs-share/data/egov-search/config"
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: egov-search-config-pvc-nfs
  namespace: egov-app
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 1Mi
  volumeName: egov-search-config-pv-nfs
  storageClassName: standard
---
# Model PV/PVC - NFS
apiVersion: v1
kind: PersistentVolume
metadata:
  name: egov-search-model-pv-nfs
  namespace: egov-app
spec:
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain
  storageClassName: standard
  nfs:
    server: 192.168.64.1
    path: "/Users/chrisyoon/nfs-share/data/egov-search/model"
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: egov-search-model-pvc-nfs
  namespace: egov-app
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 1Gi
  volumeName: egov-search-model-pv-nfs
  storageClassName: standard
---
# Example PV/PVC - NFS
apiVersion: v1
kind: PersistentVolume
metadata:
  name: egov-search-example-pv-nfs
  namespace: egov-app
spec:
  capacity:
    storage: 1Mi
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain
  storageClassName: standard
  nfs:
    server: 192.168.64.1
    path: "/Users/chrisyoon/nfs-share/data/egov-search/example"
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: egov-search-example-pvc-nfs
  namespace: egov-app
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 1Mi
  volumeName: egov-search-example-pv-nfs
  storageClassName: standard
---
# Cacerts PV/PVC - NFS
apiVersion: v1
kind: PersistentVolume
metadata:
  name: egov-search-cacerts-pv-nfs
  namespace: egov-app
spec:
  capacity:
    storage: 1Mi
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain
  storageClassName: standard
  nfs:
    server: 192.168.64.1
    path: "/Users/chrisyoon/nfs-share/data/egov-search/cacerts"
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: egov-search-cacerts-pvc-nfs
  namespace: egov-app
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 1Mi
  volumeName: egov-search-cacerts-pv-nfs
  storageClassName: standard
