# NFS PersistentVolume
apiVersion: v1
kind: PersistentVolume
metadata:
  name: egov-mobileid-pv-nfs
  namespace: egov-app
spec:
  capacity:
    storage: 10Mi
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain
  storageClassName: standard
  nfs:
    server: 192.168.64.1
    path: "/Users/chrisyoon/nfs-share/data/egov-mobileid/config"

---
# NFS PersistentVolumeClaim
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: egov-mobileid-pvc-nfs
  namespace: egov-app
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 10Mi
  volumeName: egov-mobileid-pv-nfs
  storageClassName: standard
