apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: sonarqube-pvc-local
  namespace: egov-cicd
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi
  storageClassName: local-path
